accounts/urls.py
from django.urls import path
from .views import IndexView,ProfileView,ProfileEditView,LoginView,LogoutView,SignupView
app_name = "accounts"
urlpatterns = [
    path("profile/", ProfileView.as_view(), name="profile"),
    path("profile/edit", ProfileEditView.as_view(), name="profile_edit"),
    path("login/", LoginView.as_view(), name="account_login"),
    path("logout/", LogoutView.as_view(), name="account_logout"),
    path("signup/", SignupView.as_view(), name="account_signup"),
]

blog/urls.py
from django.urls import path
from .views import BlogListView,BlogDetailView
app_name = "blog"
urlpatterns = [
    path('',BlogListView.as_view(),name="blog"),
    path('<int:pk>/',BlogDetailView.as_view(),name="blog_detail"),
]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar
from django.views.generic import TemplateView

import os
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
import environ
env = environ.Env()
env.read_env(os.path.join(BASE_DIR, '.env'))
ADMIN_URL = env('ADMIN_URL')

urlpatterns = [
    path(ADMIN_URL + '/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('blog/', include('blog.urls')),
    path('markdownx/', include('markdownx.urls')),
    path("accounts/",include("accounts.urls")),
    path("", include("pencaseapp.urls")),
    path('privacy-policy/',TemplateView.as_view(template_name="privacypolicy.html"),name="privacy-policy"),
    path('consent/',TemplateView.as_view(template_name="consent.html"),name="consent"),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    print(settings.DEBUG)
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ] 

pencaseapp/urls.py
from django.urls import path
from .views import (ArticleListView,
                    ArticleDetailView,
                    CommentCreateView,
                    ArticleCreateView,
                    ArticleUpdateView,
                    ArticleDeleteView,
                    LikeView,
                    ArticleRandomListView,
                    ReplyCreateView,
                    ArticleLatestOrderListView,
                    ArticleLikeOrderListView,
                    MyPageView)
from django.views.generic import TemplateView

app_name="pencaseapp"
urlpatterns = [
    path('',ArticleListView.as_view(),name="home"),
    path('trend/',ArticleLikeOrderListView.as_view(),name="trend"),
    path('latest/',ArticleLatestOrderListView.as_view(),name="latest"),
    path('random/',ArticleRandomListView.as_view(),name="random"),
    path('mypage/',MyPageView.as_view(),name="mypage"),
    path('pencase/<int:pk>/',ArticleDetailView.as_view(),name="article_detail"),
    path('comment/<int:pk>/',CommentCreateView.as_view(),name="pencase_comment"),
    path('reply/<int:pk>/',ReplyCreateView.as_view(),name="pencase_reply"),
    path('create/',ArticleCreateView.as_view(),name="article_create"),
    path('update/<int:pk>/',ArticleUpdateView.as_view(),name="article_update"),
    path('delete/<int:pk>/',ArticleDeleteView.as_view(),name="article_delete"),
    path('like/<int:pk>/',LikeView,name="article_likes"),
    
]

pencaseapp/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from imagekit.models import ImageSpecField, ProcessedImageField
from imagekit.processors import ResizeToFill

class Article(models.Model):
    # origin_image = models.ImageField('サムネイル',upload_to="media/%Y/%m/%d", height_field=None,null=True, width_field=None, max_length=None)
    thumbnail = ProcessedImageField(
                                    upload_to="media/%Y/%m/%d",
                                    processors=[ResizeToFill(960,540)],
                                    format="JPEG",
                                    options={'quality': 90},
                                    )
    theme = models.TextField('テーマ')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT)
    pencase = models.TextField("筆箱")
    mechanical_pencil = models.TextField("シャーペン")
    ball_point_pen = models.TextField("ボールペン")
    eraser = models.TextField("消しゴム")
    others = models.TextField("その他")
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True, auto_now_add=False)
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="article_likes")
    def get_total_likes(self):
        return self.likes.count()
    def __str__(self):
        return self.theme
    
class Comment(models.Model):
    comment_text = models.TextField()
    commentator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT,)
    created_at = models.DateTimeField(auto_now=True, auto_now_add=False)
    comment_target = models.ForeignKey(Article, related_name="comments",on_delete=models.CASCADE)
    def __str__(self):
        return self.text[:10]
    
class Reply(models.Model):
    reply_target = models.ForeignKey(Comment, related_name="replies", on_delete=models.CASCADE)
    replyer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT)
    reply_text = models.TextField()
    created_at = models.DateTimeField(auto_now=False, auto_now_add=True)
    def __str__(self):
        return self.text[:10]

pencaseapp/forms.py
from django import forms
from .models import Comment,Article,Reply

class ProtectSpamForm(forms.CharField):
    """override Field"""
    
    def __init__(self, label="荒らし対策",**kwargs):
        super().__init__(required=True, label=label,**kwargs)
        self.widget.attrs['placeholder'] = '「ふでばこ」を漢字に変換してください。'
    def clean(self, value):
        value = super().clean(value)
        if value == '筆箱':
            return value
        else:
            raise forms.ValidationError('違います。')

class CommentCreateForm(forms.ModelForm):

    captha = ProtectSpamForm(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
    )
    class Meta:
        model = Comment
        exclude = ('created_at','comment_target', 'commentator',)
        widgets = {
            'comment_text': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': '相手を傷つけないように注意しましょう。\n※自分の投稿にはコメントできません。'
                })
        }
        labels = {
            'comment_text':'感想を入力してください。'
        }


class ReplyCreateForm(forms.ModelForm):
    class Meta:
        model = Reply
        exclude = ('replyer','created_at','reply_target',)
        widgets = {
            'reply_text': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder':'返事を記入してください。'
                })
        }
        labels = {
            'reply_text':'返事'
        }


class ArticleCreateForm(forms.ModelForm):
    class Meta:
        model = Article
        exclude = ('author', 'created_at', 'updated_at', 'likes')
        labels = {
            'thumbnail':'サムネイル'
        }
        widgets = {
            'theme': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': '自分の筆箱のテーマを入力してください。',
                'rows':'5'
                }),
            'pencase': forms.Textarea(attrs={
                'class':'form-control',
                'placeholder':'自分の筆箱の解説をしてください。\n書くことがなければ、「なし」などと記入してください。\n例えば、使っている筆箱は、ユナイテッドビーズのバトンペンケースです。'
                }),
            'mechanical_pencil': forms.Textarea(attrs={
                'class':'form-control',
                'placeholder':'自分のシャーペンの解説をしてください。\n書くことがなければ、「なし」などと記入してください。\n例えば、使っているシャーペンは、s20とクルトガアドバンスなどです。\ns20の良いところは...です。\nでも、値段が少し高いので扱いには注意しています。'
                }),
            'ball_point_pen': forms.Textarea(attrs={
                'class':'form-control',
                'placeholder':'自分のボールペンの解説をしてください。\n書くことがなければ、「なし」などと記入してください。\n例えば、使っているボールペンは、ゼブラのサラサがほとんどです。\n買いやすく、発色もいいので気に入っています。'
                }),
            'eraser': forms.Textarea(attrs={
                'class':'form-control',
                'placeholder':'自分の消しゴムの解説をしてください。\n書くことがなければ、「なし」などと記入してください。\n例えば、無難にMONOを使っています。\n折れやすいのが嫌ですが、安くて消しやすいです。'
                }),
            'others': forms.Textarea(attrs={
                'class':'form-control',
                'placeholder':'その他の文房具の解説をしてください。\n書くことがなければ、「なし」などと記入してください。\n例えば、定規はアルミアンドウッド定規、シャー芯はハイユニがお気に入りです。'
                }),
        }

pencaseapp/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.views.generic import ListView,DetailView,CreateView,UpdateView,DeleteView
from .models import Article, Comment,Reply
from .forms import CommentCreateForm,ArticleCreateForm,ReplyCreateForm
from django.contrib.auth.mixins import LoginRequiredMixin,UserPassesTestMixin
from django.shortcuts import reverse,resolve_url
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Count

class EditDeleteOnlyAuthorMixin(UserPassesTestMixin):
    raise_exception = True
    def test_func(self):
        self.object = self.get_object()
        return self.request.user == self.object.author

@login_required
def LikeView(request, pk):
    article = get_object_or_404(Article, pk=pk)
    if request.user == article.author:
        messages.add_message(request, messages.INFO, '自分の投稿にいいねできません。')
    else:
        if article.likes.filter(pk=request.user.pk).exists():
            article.likes.remove(request.user)
        else:    
            article.likes.add(request.user)
    return HttpResponseRedirect(reverse("pencaseapp:article_detail",args=[str(pk)]))

"""TopPage"""
class ArticleListView(ListView):
    model = Article
    template_name = "pencaseapp/index.html"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["article_trend"] = Article.objects.annotate(like_count=Count('likes')).order_by('-like_count')[:6]
        context["article_latest"] = Article.objects.order_by('-created_at')[:6]
        return context

"""Random"""    
class ArticleRandomListView(ListView):
    model = Article
    template_name = "pencaseapp/random.html"
    ordering = '?'
    paginate_by = 12

"""Latest"""
class ArticleLatestOrderListView(ListView):
    model = Article
    template_name = "pencaseapp/latest.html"
    ordering = '-created_at'
    paginate_by = 12

"""Trend"""
class ArticleLikeOrderListView(ListView):
    model = Article
    template_name = "pencaseapp/trend.html"
    paginate_by = 12
    def get_queryset(self):
        return Article.objects.annotate(like_count=Count('likes')).order_by('-like_count')
    

class ArticleUpdateView(EditDeleteOnlyAuthorMixin, UpdateView):
    model = Article
    template_name = "pencaseapp/article_form.html"
    form_class = ArticleCreateForm
    def get_success_url(self):
        messages.add_message(self.request, messages.SUCCESS, '投稿が更新されました。')
        return reverse('pencaseapp:article_detail',kwargs={"pk":self.kwargs['pk']})
    def form_valid(self, form):
        return super().form_valid(form)
    def form_invalid(self, form):
        return super().form_invalid(form)

class ArticleDeleteView(EditDeleteOnlyAuthorMixin, DeleteView):
    model = Article
    template_name = "pencaseapp/article_delete.html"
    def get_success_url(self):
        messages.add_message(self.request, messages.SUCCESS, '投稿が削除されました。')
        return reverse('pencaseapp:home')
    def delete(self, request, *args, **kwargs):
        return super().delete(request, *args, **kwargs)

class ArticleCreateView(LoginRequiredMixin,CreateView):
    model = Article
    template_name = "pencaseapp/article_form.html"
    form_class = ArticleCreateForm
    login_url = 'accounts:account_login'
    def form_valid(self, form):
        article = form.save(commit=False)
        article.author = self.request.user
        article.save()
        messages.success(self.request,'投稿が完了しました。画像の下から、ツイッターに共有しましょう！')
        return super().form_valid(form)
    def get_success_url(self):
        return reverse('pencaseapp:article_detail', kwargs={"pk": self.object.pk})
        
class MyPageView(LoginRequiredMixin, ListView):
    model = Article
    template_name = "pencaseapp/mypage.html"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["myarticle"] = Article.objects.filter(author=self.request.user)
        return context
    

class ArticleDetailView(DetailView):
    model = Article
    template_name = "pencaseapp/detail.html"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        aim = get_object_or_404(Article, id=self.kwargs['pk'])
        total_likes = aim.get_total_likes()
        context["total_likes"] = total_likes
        return context
    

class CommentCreateView(LoginRequiredMixin,CreateView):
    model = Comment
    form_class = CommentCreateForm
    template_name = "pencaseapp/comment_form.html"
    redirect_field_name = 'pencaseapp:home'
    login_url = 'accounts:account_login'
    def form_valid(self, form):
        pencase_pk = self.kwargs['pk']
        pencase = get_object_or_404(Article, pk=pencase_pk)
        comment = form.save(commit=False)
        comment.comment_target = pencase
        comment.commentator = self.request.user
        if (pencase.author == comment.commentator):
            messages.add_message(self.request, messages.INFO, '自分の投稿にはコメントできません。返信することはできます。')
            return redirect('pencaseapp:article_detail', pk=comment.comment_target.pk)
        comment.save()
        return redirect('pencaseapp:article_detail',pk=pencase_pk)

class ReplyCreateView(LoginRequiredMixin,CreateView):
    model = Reply
    form_class = ReplyCreateForm
    template_name = "pencaseapp/reply_form.html"
    redirect_field_name = 'pencaseapp:home'
    login_url = 'accounts:account_login'
    def form_valid(self, form):
        comment_pk = self.kwargs['pk']
        comment = get_object_or_404(Comment, pk=comment_pk)
        reply = form.save(commit=False)
        reply.reply_target = comment
        reply.replyer = self.request.user
        reply.save()
        messages.add_message(self.request, messages.INFO, '返事が送信されました。')
        return redirect('pencaseapp:article_detail', pk=comment.comment_target.pk)

templates/pencaseapp/article_delete.html
{% extends "base.html" %}
{% load static %}

{% block content %}   
  <form  method="POST">
      {% csrf_token %}
      <h3>本当に削除してよろしいですか？</h3>
<button type="submit" class="btn btn-outline-danger waves-effect">削除する</button>
<a href="{{request.META.HTTP_REFERER}}" class="btn btn-outline-primary waves-effect　">戻る</a>  </form>
{% endblock content %}   

templates/pencaseapp/article_form.html
{% extends "base.html" %}
{% load static %}

{% block content %}  
<div class="mb-4">

    <form  method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        {{form.media}}
        <button type="submit" class="btn btn-outline-primary waves-effect">投稿する</button>
        <a href="{{request.META.HTTP_REFERER}}" class="btn btn-outline-danger waves-effect">戻る</a>
    </form>
</div> 
{% endblock content %}   

templates/pencaseapp/detail.html
{% extends "base.html" %} {% load static %} 
{% block thumbnail %}{{ object.thumbnail.url }}{% endblock thumbnail %}
{% block content %}
<div class="text-center">

    <div class="row">

        <!--Grid column-->
        <div class="col-lg-12 col-md-12 mb-4">
            <!--Card-->
            <div class="card ">
                <!--Card image-->
                <div class="view overlay">
                    <img src="{{ object.thumbnail.url }}" class="card-img-top" alt="" loading="lazy">
                    <br>
                    <small>{{object.author.nickname}}さんの筆箱</small><br />
                    <div class="text-right mr-4">
                    <small>{{object.created_at|date}}に公開</small><br />
                    <small>{{object.updated_at|date}}に更新</small><br />
                    </div>
                </div>

                <!--Card content-->
                <div class="card-body">
                    {% if request.user == object.author %}
                    <p>投稿したら、下のボタンから<br>ツイートしましょう！</p>
                    <a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="twitter-share-button"
                        data-size="large" data-text="筆箱紹介を投稿しました！ #筆箱紹介 #文房具好きと繋がりたい #みんなの筆箱紹介" data-lang="ja"
                        data-show-count="false">Tweet</a>
                    <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script><br>
                    {% else %}
                    <p>下のボタンから<br>ツイッターでシェアしましょう！</p>
                    <a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="twitter-share-button"
                        data-size="large" data-text="いい筆箱! #筆箱紹介 #文房具好きと繋がりたい #みんなの筆箱紹介" data-lang="ja"
                        data-show-count="false">Tweet</a>
                    <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script><br>
                    {% endif %}
                    {% if request.user == object.author %}
                    <a class="btn btn-danger" href="{% url 'pencaseapp:article_delete' object.pk %}"><i
                            class="fas fa-trash"></i>
                        削除する</a>
                    {% endif %} {% if request.user == object.author %}
                    <a class="btn btn-light" href="{% url 'pencaseapp:article_update' object.pk %}"><i
                            class="fas fa-pen"></i>
                        編集</a>
                    {% endif %}
                    <!--Title-->
                    <hr>
                
                    <div class="text-left mt-2">
                        <h3 class="article__title"><i class="fas fa-flag"></i> テーマ</h3>
                        <p class="article__content">{{object.theme|linebreaks}}</p>
                        <hr class="my-4">
                        <h3 class="article__title"><i class="fas fa-folder-open"></i> 筆箱</h3>
                        <p class="article__content">{{object.pencase|linebreaks}}</p>
                        <hr class="my-4">
                        <h3 class="article__title"><i class="fas fa-pencil-alt"></i> シャーペン</h3>
                        <p class="article__content">{{object.mechanical_pencil|linebreaks}}</p>
                        <hr class="my-4">
                        <h3 class="article__title"><i class="fas fa-pen-alt"></i> ボールペン</h3>
                        <p class="article__content">{{object.ball_point_pen|linebreaks}}</p>
                        <hr class="my-4">
                        <h3 class="article__title"><i class="fas fa-eraser"></i>消しゴム</h3>
                        <p class="article__content">{{object.eraser|linebreaks}}</p>
                        <hr class="my-4">
                        <h3 class="article__title"><i class="fas fa-cubes"></i>その他</h3>
                        <p class="article__content">{{object.others|linebreaks}}</p>
                        <hr class="my-4">
                    </div>

                <form action="{% url 'pencaseapp:article_likes' object.pk %}" method="POST">
                    {% csrf_token %}
                    <button class="btn btn-outline-danger btn-rounded waves-effect btn-sm" type="submit">
                        <i class="far fas fa-heart"></i> {{total_likes}} いいね
                    </button>
                </form>
                
                {% if request.user != object.author %}
                <a class="btn btn-outline-info btn-rounded waves-effect btn-sm"
                    href="{% url 'pencaseapp:pencase_comment' object.pk %}"><i class="fas fa-comment"></i> コメントする</a>
                {% endif %}

                </div>
            </div>
            <!--/.Card-->
        </div>
        <!--Grid column-->
    </div>
    <a class="btn btn-blue-grey mb-4" href="{% url 'pencaseapp:home'%}"><i class="fas fa-backward"></i> 戻る</a>
    <div class="card grey lighten-4 chat-room">
        <div class="card-body">
            <h3 class="mb-4">感想・返信</h3>
            {% for comment in object.comments.all %}
            <hr>
            <div class="row px-2">
                <!-- Grid column -->
                <div class="col-md-6 col-xl-8 pl-md-3 px-lg-auto px-0">
                    <div class="chat-message">
                        <ul class="list-unstyled chat">
                            <li class="d-flex justify-content-between mb-4">
                                <div class="chat-body white p-3 ml-2 z-depth-1">
                                    <div class="header">
                                        <small class="primary-font">{{comment.commentator.nickname}}さん</small>
                                        <small class="pull-right text-muted"><i
                                                class="far fa-clock"></i>{{comment.created_at}}</small>
                                    </div>
                                    <p class="mb-0 text-left">{{comment.comment_text}}</p>
                                </div>
                            </li>
                            <div>
                                <a class="btn btn-info btn-sm waves-effect waves-light float-right"
                                    href="{% url 'pencaseapp:pencase_reply' comment.pk  %}">返信する</a>
                                </a>
                            </div>
                            <br><br>

                            {% for reply in comment.replies.all %}
                            <li class=" mr-2 offset-ml-lg-3 ml-0 "></li>
                            <li class="d-flex justify-content-between mb-4">
                                <div class="chat-body gray p-3 ml-2 z-depth-1">
                                    <div class="header">
                                        <small class="primary-font">{{reply.replyer.nickname}}さん</small>
                                        <small class="pull-right text-muted"><i class="far fa-clock"></i>
                                            {{reply.created_at}}</small>
                                    </div>
                                    <p class="mb-0 text-left">{{reply.reply_text}}</p>
                                </div>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                <!-- Grid column -->
            </div>
            <!-- Grid row -->
            {% empty %}
            <p>コメントはまだありません。</p>
            {% endfor %}
        </div>
    </div>
    <a class="btn btn-blue-grey my-4" href="{% url 'pencaseapp:home'%}"><i class="fas fa-backward"></i> 戻る</a>
    {% endblock content %}

templates/pencaseapp/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    {% include 'pencaseapp/top.html' %}
<main>
    <div class="text-center">
        <div class="card blue lighten-5 my-4 py-4 px-4">
            <p>このページでは話題、最新の筆箱を見学することができます。</p>
            <p>左上でメニューへ、トップ画像でホームへ、そして右上からログインできます。</p>
        </div>
        <h2 class="my-4">話題の筆箱</h2>
        <div class="row">

            {% for object in article_trend %}
            <!--Grid column-->
            <div class="col-lg-4 col-md-12 my-4">
                <!--Card-->
                <div class="card">
                    <!--Card image-->
                    <div class="view overlay">
                        <img src="{{ object.thumbnail.url }}" class="card-img-top " alt="" loading="lazy">
                        <a href="{% url 'pencaseapp:article_detail' object.pk %}">
                            <div class="mask rgba-white-slight"></div>
                        </a>
                    </div>

                    <!--Card content-->
                    <div class="card-body pt-0">
                        <!--Title-->
                        <h4 class="card-title">{{object.title}}</h4>
                        <!--Text-->

                        <a href="{% url 'pencaseapp:article_detail' object.pk %}"
                            class="btn btn-light-blue btn-sm mb-1">
                            <i class="fas fa-angle-double-right "></i>
                            詳しくみる！</a><br>
                        <a><i class="fas fa-heart" style="color: #ff80ab;"></i> {{object.likes.count}}</a><span
                            class="mx-1"></span><a><i class="fas fa-comment" style="color: #b2ff59 ;"></i>
                            {{object.comments.all.count}}</a>
                    </div>
                </div>
                <!--/.Card-->
            </div>
            <!--Grid column-->
            <br />
            {% empty %}
            <p>まだ投稿がありません</p>
            {% endfor %}
        </div>
        <a class="btn btn-info btn-rounded" href="{% url 'pencaseapp:trend' %}">話題の筆箱をすべて見る <i
                class="far fa-arrow-alt-circle-right"></i></a>
    </div>
    <hr class="my-4">

    <div class="text-center ">
        <h2 class="my-4">最新の筆箱</h2>
        <div class="row">
            {% for object in article_latest %}
            <!--Grid column-->
            <div class="col-lg-4 col-md-12 my-4">
                <!--Card-->
                <div class="card">
                    <!--Card image-->
                    <div class="view overlay">
                        <img src="{{ object.thumbnail.url }}" class="card-img-top" alt="" loading="lazy">
                        <a href="{% url 'pencaseapp:article_detail' object.pk %}">
                            <div class="mask rgba-white-slight"></div>
                        </a>
                    </div>
                    <!--Card content-->
                    <div class="card-body">
                        <a href="{% url 'pencaseapp:article_detail' object.pk %}" class="btn btn-light-blue btn-sm">
                            <i class="fas fa-angle-double-right"></i>
                            詳しくみる！</a><br>
                        <a><i class="fas fa-heart" style="color: #ff80ab;"></i> {{object.likes.count}}</a>
                        <a><i class="fas fa-comment" style="color: #b2ff59 ;"></i> {{object.comments.all.count}}</a>
                    </div>
                </div>
                <!--/.Card-->
            </div>
            <!--Grid column-->
            <br />
            {% empty %}
            <p>まだ投稿がありません</p>
            {% endfor %}
        </div>
    <a class="btn btn-info btn-rounded mb-4" href="{% url 'pencaseapp:latest' %}">最新の筆箱をすべて見る <i
            class="far fa-arrow-alt-circle-right"></i></a>
    </div>
    {% include "pencaseapp/post_button.html" %}

    </div>

</main>

{% endblock content %}

templates/pencaseapp/mypage.html
   {% extends 'base.html' %}
   {% block content %}
   <div class="text-center">
   <div class="card  blue lighten-5 my-4 py-4 px-4 text-left">
       <p>このページでは</p>
       <ul>
       <li>ニックネームの変更</li>
       <li>自分の投稿の管理</li>
       <li>ログアウト</li>
       </ul>
       <p>ができます。</p>
   </div>
       <h2>プロフィール</h2>
       <p>ニックネーム：{{ request.user.nickname }}</p>
       <a class="btn btn-info" href="{% url 'accounts:profile_edit' %}">ニックネームを変更</a>
       <h2 class="mt-4">自分の投稿一覧</h2>
       <div class="row">
           {% for object in myarticle %}
           <div class="col-lg-4 col-md-12 my-4">
               <!--Card-->
               <div class="card">
                   <!--Card image-->
                   <div class="view overlay">
                       <img src="{{ object.thumbnail.url }}" class="card-img-top" alt="" loading="lazy">
                       <a href="{% url 'pencaseapp:article_detail' object.pk %}">
                           <div class="mask rgba-white-slight"></div>
                       </a>
                   </div>

                   <!--Card content-->
                   <div class="card-body mt-0">
                       <!--Title-->
                       <h4 class="card-title">{{object.title}}</h4>
                       <!--Text-->

                       <a href="{% url 'pencaseapp:article_detail' object.pk %}" class="btn btn-light-blue btn-sm mb-1">
                           <i class="fas fa-angle-double-right "></i>
                           詳しくみる！</a><br>
                       <a><i class="fas fa-heart" style="color: #ff80ab;"></i> {{object.likes.count}}</a><span
                           class="mx-1"></span><a><i class="fas fa-comment" style="color: #b2ff59 ;"></i>
                           {{object.comments.all.count}}</a>
                   </div>
               </div>
               <!--/.Card-->
           </div>
           <!--Grid column-->
           <br />
           {% empty %}
           <p>no content</p>
           {% endfor %}
       </div>
       <a href="{% url 'accounts:account_logout' %}" class="btn btn-danger">
           ログアウト</a>
   </div>
       {% include 'pagenation.html' %}

   </div>
   {% endblock content %}

templates/pencaseapp/post_button.html
<a href="{% url 'pencaseapp:article_create' %}"
        class="fixed-right-bottom btn-floating btn btn-success btn-rounded "><i class="fas fa-pencil-alt"></i>
        投稿する！</a>

templates/pencaseapp/top.html
<div class="text-center">
        <div class="top-title white">
        <h2 class="mb-4">ようこそ、<br>みんなの筆箱へ。</h2>
        </div>
    </div>