blog/urls.py
from django.urls import path
from .views import BlogListView,BlogDetailView
app_name = "blog"
urlpatterns = [
    path('',BlogListView.as_view(),name="blog"),
    path('<int:pk>/',BlogDetailView.as_view(),name="blog_detail"),
]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar
from django.views.generic import TemplateView

import os
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
import environ
env = environ.Env()
env.read_env(os.path.join(BASE_DIR, '.env'))
ADMIN_URL = env('ADMIN_URL')

urlpatterns = [
    path(ADMIN_URL + '/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('blog/', include('blog.urls')),
    path('markdownx/', include('markdownx.urls')),
    path("accounts/",include("accounts.urls")),
    path("", include("pencaseapp.urls")),
    path('privacy-policy/',TemplateView.as_view(template_name="privacypolicy.html"),name="privacy-policy"),
    path('consent/',TemplateView.as_view(template_name="consent.html"),name="consent"),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    print(settings.DEBUG)
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ] 

blog/models.py
from django.db import models
from markdownx.models import MarkdownxField
from markdownx.utils import markdownify
from django.utils import timezone
class Category(models.Model):
    name = models.CharField(max_length=50)
    def __str__(self):
        return self.name
    

class Blog(models.Model):
    title = models.CharField('タイトル',max_length=50)
    text = MarkdownxField('本文')
    thumbnail = models.ImageField("サムネイル", upload_to="media/blog/%Y/%m/%d", height_field=None, width_field=None, max_length=None)
    category = models.ForeignKey(Category, related_name="category", on_delete=models.CASCADE)
    meta_description = models.TextField("メタディスクリプション",blank=True)
    created_at = models.DateTimeField('作成日',default=timezone.now)
    updated_at = models.DateTimeField('更新日',auto_now=True, auto_now_add=False)
    is_public = models.BooleanField('公開',default=False)
    def __str__(self):
        return self.title

    def formatted_markdown(self):
        return markdownify(self.text)
    class Meta:
        ordering = ['-created_at']

blog/views.py
from django.shortcuts import render
from .models import Blog
from django.views import generic
from django.contrib.auth.mixins import UserPassesTestMixin
from django.http import Http404  

# class OnlySuperUserMixin(UserPassesTestMixin):
#     raise_exception = True
#     def test_func(self):
#         user = self.request.user
#         return  user.is_superuser

class BlogListView(generic.ListView):
    model = Blog
    template_name = "blog/blog.html"
    paginate_by = 9
    ordering = '-created_at'
    queryset = Blog.objects.filter(is_public=True)

class BlogDetailView(generic.DetailView):
    model = Blog
    template_name = "blog/blog_detail.html"
    def get_object(self, queryset=None):
        Blog = super().get_object()
        if Blog.is_public :
            return Blog
        else:
            raise Http404

templates/blog/blog.html
{% extends "base.html" %}
{% load static %}
{% block title %}みんなの筆箱紹介！|{% endblock %}
{% block content %}
<div id="blog">
<!-- Section: Blog v.1 -->
<section class="my-5 c">
    <!-- Section heading -->
    <h2 class="h1-responsive font-weight-bold text-center my-5">公式ブログ</h2>
    <!-- Section description -->
    <div class="card  blue lighten-5 my-4 py-4 px-4">
    <p class="text-center w-responsive mx-auto ">お知らせや、このサイトの使い方を載せております。</p>
    <p class="text-center w-responsive mx-auto ">他にも、文房具の情報を載せていきます。</p>
    </div>
    <hr class="my-6">
    <!-- Grid row -->
    <div class="row">
        {% for post  in object_list %}
        {% if post.is_public %}

        <!-- Grid column -->
        <div class="col-lg-5">

            <!-- Featured image -->
            <div class="view overlay rounded z-depth-2 mb-lg-0 mb-4">
                
                {% if post.thumbnail.exist %}
                <img class="img-fluid" src="{{ post.thumbnail.url }}"
                    alt="Sample image">
                {% endif %}
                <img class="img-fluid" src="{% static 'blogimage.png' %}"
                    alt="Sample image">
                <a>
                    <div class="mask rgba-white-slight"></div>
                </a>
            </div>

        </div>
        <!-- Grid column -->
        <!-- Grid column -->
        <div class="col-lg-7">

            <!-- Category -->
            <a class="green-text">
                <h6 class="font-weight-bold mb-3"> <i class="fas fa-bullseye"></i>{{post.category}}</h6>
            </a>
            <!-- Post title -->
            <h3 class="font-weight-bold mb-3"><strong>{{ post.title|safe}}</strong></h3>
            <!-- Excerpt -->
            <p>{{ post.meta_description}}
            </p>
            <!-- Post data -->
            <p>作成日：{{ post.created_at |date:"Y年n月j日"}}</p>
            <!-- Read more button -->
            <a class="btn btn-success btn-md" href="{% url 'blog:blog_detail' post.pk %}">全部読む</a>

        <hr class="my-5">
        </div>
        <!-- Grid column -->

        {% endif %}
        {% endfor %}
    </div>
    <!-- Grid row -->


</section>
</div>


{% endblock content %}

templates/blog/blog_detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}みんなの筆箱紹介！{% endblock %}

{% block meta-description %}みんなが自由に自分の筆箱を紹介しあえるウェブサービスです。写真を載せることができ、いいね、コメントも可能。投稿も登録だけでかんたんにすることができます。{% endblock meta-description %}
{% load static %}
{% block content %}
<div id="blog">
    <div class="card white px-4 pb-4 pt-2 mb-4">
        <h1 class="h2-responsive font-weight-bold text-center my-5">{{ object.title }}</h1>
         <img src="{% block thumbnail %}{{ object.thumbnail.url }}{% endblock thumbnail %}" class="card-img-top" alt=""
             loading="lazy">
         <br>
        <div class="text-right mb-2">
            <small>作成日：{{object.created_at|date:"Y年n月j日"}}</small>
            <small>更新日：{{object.created_at|date:"Y年n月j日"}}</small>
        </div>
            {{ object.formatted_markdown|safe }}
    </div>
</div>
{% endblock content %}